import { LiteralEnum } from '@/lib/types/literal-enum';

export const OtakuReactionApiKeys = {
  Airkiss: 'airkiss',
  Angrystare: 'angrystare',
  Bite: 'bite',
  Bleh: 'bleh',
  Blush: 'blush',
  Brofist: 'brofist',
  Celebrate: 'celebrate',
  Cheers: 'cheers',
  Clap: 'clap',
  Confused: 'confused',
  Cool: 'cool',
  Cry: 'cry',
  Cuddle: 'cuddle',
  Dance: 'dance',
  Drool: 'drool',
  Evillaugh: 'evillaugh',
  Facepalm: 'facepalm',
  Handhold: 'handhold',
  Happy: 'happy',
  Headbang: 'headbang',
  Hug: 'hug',
  Huh: 'huh',
  Kiss: 'kiss',
  Laugh: 'laugh',
  Lick: 'lick',
  Love: 'love',
  Mad: 'mad',
  Nervous: 'nervous',
  No: 'no',
  Nom: 'nom',
  Nosebleed: 'nosebleed',
  Nuzzle: 'nuzzle',
  Nyah: 'nyah',
  Pat: 'pat',
  Peek: 'peek',
  Pinch: 'pinch',
  Poke: 'poke',
  Pout: 'pout',
  Punch: 'punch',
  Roll: 'roll',
  Run: 'run',
  Sad: 'sad',
  Scared: 'scared',
  Shout: 'shout',
  Shrug: 'shrug',
  Shy: 'shy',
  Sigh: 'sigh',
  Sip: 'sip',
  Slap: 'slap',
  Sleep: 'sleep',
  Slowclap: 'slowclap',
  Smack: 'smack',
  Smile: 'smile',
  Smug: 'smug',
  Sneeze: 'sneeze',
  Sorry: 'sorry',
  Stare: 'stare',
  Stop: 'stop',
  Surprised: 'surprised',
  Sweat: 'sweat',
  Thumbsup: 'thumbsup',
  Tickle: 'tickle',
  Tired: 'tired',
  Wave: 'wave',
  Wink: 'wink',
  Woah: 'woah',
  Yawn: 'yawn',
  Yay: 'yay',
  Yes: 'yes',
} as const;

export type OtakuReactionApiKeys = LiteralEnum<typeof OtakuReactionApiKeys>;

export interface SingleReactionResponse {
  url: string;
}

export interface AllReactionsResponse {
  reactions: OtakuReactionApiKeys[];
}
